@startmindmap
* 學精第一
** 006 刻意練習
** 078 最高學習效率=15.87%
** 090 正確的學習方法隻有一種風格
** 096 提高學習成績的最簡單的心法
** 105 忘記是為了更好的記住
** 113 反脆弱式學習養生法
@endmindmap

@startmindmap
* 學習是什麼
** 學精第一
*** 006 刻意練習
*** 078 最高學習效率=15.87%
*** 090 正確的學習方法隻有一種風格
*** 096 提高學習成績的最簡單的心法
*** 105 忘記是為了更好的記住
*** 113 反脆弱式學習養生法
** 學廣第二
*** 122 自由技藝
*** 137 屠龍術的日常應用
*** 151 從‘’刻意練習‘’到“功夫在詩外”
*** 162 深度對廣度
** 創造第三
*** 174 到底什麼是發散思維
*** 190 怎樣“不”集中註意力
*** 197 創造的腳手架
*** 205 秘密項目
*** 215 創作者的悖論
*** 227 修煉你的文化自覺
** 策略第四
*** 240 “自學”的學問
*** 261 學習的快功和慢功
*** 271 有關學校教育的大實話
*** 279 每條路都是少有人走的路
*** 287 兩種技能增長麯線
** 兵器第五
*** 298 談談寫作和研究
*** 308 好思想都在哪裏
**** 怎麼找值得看的好書？
***** 看推薦
***** 看書評
***** 看作者
*** 317 厚道的人應該怎麼使用思維導圖
*** 325 我怎樣管理信息
*** 337 強力研讀筆記法
** 無為第六
*** 350 莊子“無為”的一種科學解釋
*** 359 主動操作大腦
*** 368 天才和瘋子的一線之隔
*** 376 內隱學習和外顯學習
*** 387 註釋
@endmindmap
